- client/enemyPathing.js
- client/level1State.js
- package-lock.json
- package.json
> implemented basic pathfinding for enemies

- client/level1State.js
> added pathing for all enemies

- client/enemyGenerator.js
- client/enemyPathing.js
- client/rooms/level1/level1_0.js
> moved enemy generator to another file

- client/Player.js
- client/rooms/level1/level1_0.js
> small edits

- client/Player.js
- client/collisionGroups.js
- client/enemies.js
- client/enemyGenerator.js
- client/game.js
- client/preloadState.js
- client/rooms/level1/level1_0.js
Added enemy health / dying.  Room doors open.  Level remembers enemy deaths in each room.
> added enemy damage and door opening

- client/Player.js
- client/enemyRenderer.js
- client/rooms/level1/level1_0.js
- client/socket.js
- server/socket/enemyGenerator.js
- server/socket/index.js
> Enemy ai object socket

- client/Player.js
- client/game.js
- client/rooms/level1/level1_0.js
- client/socket.js
- server/socket/index.js
> added socket shooting

- client/rooms/level1/level1_0.js
- client/socket.js
- server/socket/enemyGenerator.js
- server/socket/index.js
> Player spawning

- client/components/Game.js
- client/rooms/level1/level1_0.js
- server/socket/enemyGenerator.js
- server/socket/index.js
fixed some minor stuff / removed old code
> fixed some minor stuff / removed old code

- server/socket/enemyGenerator.js
- server/socket/index.js
> enemy pathing for only players alive

- client/Items.js
- client/Player.js
- client/enemies.js
- client/enemyRenderer.js
- client/game.js
- client/rooms/level1/level1_0.js
- client/socket.js
- server/socket/index.js
> Ui heart health before merge

- client/Items.js
- client/Player.js
> removed p1 health text

- client/Player.js
- client/enemies.js
- client/rooms/level1/level1_0.js
- client/socket.js
- server/socket/index.js
> Add boss health text

- client/components/Game.js
- public/style.css
- server/socket/index.js
> working minimap

- server/writeLevelFiles.js
> added logic to create directories if they don't exist

- client/rooms/level1/level1_0.js
> fixed p2 boss health text not updating

- client/components/Game.js
- server/socket/index.js
> working minimap update

- client/components/Game.js
- client/game.js
- client/preloadState.js
- server/socket/index.js
> Fix p2 char

- client/enemyRenderer.js
> fixed enemyHit

- client/components/Game.js
- public/style.css
> Instructions

- client/doorSensors.js
- server/socket/index.js
> removed socket info
